import Header from "@/shared/widgets/header";
import "./global.css";

export const metadata = {
  title: "Welcome to user-ui",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-slate-800 sm:px-[5vw] md:px-[7vw] lg:px-[9vw] mx-auto my-10">
        <Header />
        {children}
      </body>
    </html>
  );
}
